# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='spotify_url',
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_track_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
